From nobody Wed Jan 10 17:25:22 2018
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: Maya-Sammlung.ch
Subject: Please confirm your registration
To: hans@glueck.org
Content-Disposition: inline

Please=20click=20on=20this=20link=20to=20confirm=20your=20registration
=20
=20http://localhost:8080/registration/activate?code=3Da723d054dcd428ca58a4e=
6e8b11150b1b3571f9c